# Site settings
title: "scripts - HackTheBox"
bye_message: "Thx!"
baseurl: "/scripts/"
url: "https://wackyhacker.github.io"
disqus: wackyhacker

# Header settings
nick: "wackyhacker"
mail:
    domain: "protonmail"
    ext: "ch"
source_code:
    server: "github.com"
    nick: "wackyhacker"
blog:
    server: "wordpress.com"
    nick: "wackyhacker"
fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
