# Site settings
title: "scripts - HackTheBox"
bye_message: "Thx!"
baseurl: "/scripts/"
url: "https://wackyhacker.github.io"
disqus: wackyhacker

# Header settings
nick: "wackyhacker"
source_code:
    server: "github.com"
    nick: "wackyhacker"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
